### ISSUE TITLE
Could not find signature for dtype: <PGDialect_psycopg2, OID>

### ISSUE THREAD

**Issue by kiran0541** [GoogleCloudPlatform/professional-services-data-validator#1075]
We are using DVT for column validation on Postgres instances AWS RDS(Postgres 14.7) & CloudSQL(Postgres14) on customer environment. For one particular table we are getting an issue related to dtype. Pasting the stack trace below.

AWS DDL

```
CREATE TABLE IF NOT EXISTS public.file_details
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    doc_name character varying(255) COLLATE pg_catalog."default",
    email_id character varying(255) COLLATE pg_catalog."default",
    file_data oid,
    uploaded_date character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT file_details_pkey PRIMARY KEY (id)
)
```

GCP DDL

```
CREATE TABLE public.file_details (
    id character varying(255) NOT NULL,
    doc_name character varying(255),
    email_id character varying(255),
    file_data integer,
    uploaded_date character varying(255)
);
```

Stack Trace

```
Traceback (most recent call last):
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/multipledispatch/dispatcher.py", line 269, in __call__
    func = self._cache[types]
KeyError: (<class 'sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2'>, <class 'sqlalchemy.dialects.postgresql.base.OID'>)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/bin/data-validation", line 8, in <module>
    sys.exit(main())
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/data_validation/__main__.py", line 633, in main
    validate(args)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/data_validation/__main__.py", line 611, in validate
    run(args)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/data_validation/__main__.py", line 578, in run
    run_validations(args, config_managers)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/data_validation/__main__.py", line 534, in run_validations
    run_validation(config_manager, dry_run=args.dry_run, verbose=args.verbose)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/data_validation/__main__.py", line 507, in run_validation
    validator.execute()
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/data_validation/data_validation.py", line 96, in execute
    result_df = self._execute_validation(
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/data_validation/data_validation.py", line 270, in _execute_validation
    source_query = validation_builder.get_source_query()
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/data_validation/validation_builder.py", line 361, in get_source_query
    table = self.config_manager.get_source_ibis_table()
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/data_validation/config_manager.py", line 342, in get_source_ibis_table
    self._source_ibis_table = clients.get_ibis_table(
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/data_validation/clients.py", line 134, in get_ibis_table
    return client.table(table_name, database=database_name, schema=schema_name)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 520, in table
    return self._sqla_table_to_expr(sqla_table)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 463, in _sqla_table_to_expr
    node = self.table_class(
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/ibis/common/grounds.py", line 25, in __call__
    return cls.__create__(*args, **kwargs)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/ibis/common/grounds.py", line 99, in __create__
    return super().__create__(**kwargs)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/ibis/common/grounds.py", line 33, in __create__
    return type.__call__(cls, *args, **kwargs)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/ibis/backends/base/sql/alchemy/database.py", line 25, in __init__
    schema = sch.infer(sqla_table, schema=schema, dialect=source.con.dialect)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/ibis/backends/base/sql/alchemy/datatypes.py", line 380, in schema_from_table
    dtype = dt.dtype(dialect, column.type, nullable=column.nullable)
  File "/home/vc_dharava_mangu_zee_com/dvt/dvt/lib/python3.9/site-packages/multipledispatch/dispatcher.py", line 273, in __call__
    raise NotImplementedError(
NotImplementedError: Could not find signature for dtype: <PGDialect_psycopg2, OID>
./dvt_script_column_csql.sh: line 26: -1: substring expression < 0
```

**Comment by nj1973** [comment]
I've replaced the three PostgreSQL to PostgreSQL core type integration tests with tests using a wider range of data types, including OID.
