### ISSUE TITLE
400 Syntax error: Missing whitespace between literal and alias at [1:38] getting this error while running the query.

### ISSUE THREAD

**Issue by Nireeksha17** [GoogleCloudPlatform/professional-services-data-validator#1096]
data-validation query --conn BQ_conn -q "select * from  prj-mfy-prod-app-001-6c.mfy_dl_transactions_work.Airline"
Traceback (most recent call last):
  File "/root/professional-services-data-validator/venv/bin/data-validation", line 8, in <module>
    sys.exit(main())
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/data_validation/__main__.py", line 631, in main
    print(run_raw_query_against_connection(args))
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/data_validation/__main__.py", line 428, in run_raw_query_against_connection
    cursor = client.raw_sql(args.query)
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/ibis/backends/bigquery/__init__.py", line 258, in raw_sql
    return self._execute(query, results=results, query_parameters=query_parameters)
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/ibis/backends/bigquery/__init__.py", line 242, in _execute
    query.result()  # blocks until finished
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1520, in result
    do_get_result()
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1510, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/root/professional-services-data-validator/venv/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Missing whitespace between literal and alias at [1:38]

Location: us-central1

**Comment by nehanene15** [comment]
The following was successful for me: `data-validation query -c bq --query "select * from proj.dataset.table"` using the latest version.

Does this error occur for other tables/queries as well? Are you able to run the query successfully in BQ itself?

**Comment by piyushsarraf** [comment]
Hi @nehanene15, 
I was also not able to replicate the error, it ran successfully for me. 

I had a connect with them last week, it gives syntax error when they are doing a custom-query validation or dry running the query. However, if we run the same SQL query in the BigQuery instance, it runs successfully without giving any syntax error.

**Comment by Nireeksha17** [comment]
Hello Neha,

data-validation query -c bq --query "select * from proj.dataset.table" . We have run this still getiing the same error .

We are successfully able to run in bq the queries . But not in DVT

**Comment by nehanene15** [comment]
That's really odd. Can you try a very simple `data-validation query -c bq --query "select 1"`

**Comment by nj1973** [comment]
@Nireeksha17, I get the same error if I try to run your command. The combination of hyphens and numbers in the project name is upsetting the API. You simply need to escape your identifier. Hopefully this command should work (notice I've also used single instead of double quotes because backtick is a special bash character):
```
data-validation query --conn BQ_conn -q 'select * from `prj-mfy-prod-app-001-6c.mfy_dl_transactions_work.Airline`'
```

**Comment by Nireeksha17** [comment]
Hi Neil,

Thank for their input will check and get back to you.

Regards,
Nireeksha PK

**Comment by nehanene15** [comment]
Was this issue resolved? I will close it by EOW if there is no response.

**Comment by Nireeksha17** [comment]
Nope. We have gone with other approaches.

**Comment by nehanene15** [comment]
Closing as we are unable to replicate
