### ISSUE TITLE
PostgreSQL to AlloyDB Validation fails with error : UserWarning: Unable to create first/last aggregates: syntax error at or near "AGGREGATE"

### ISSUE THREAD

**Issue by Raniksingh** [GoogleCloudPlatform/professional-services-data-validator#1102]
**Stack Trace :** 
User has installed Python 3.10.12 and pip 22.0.2 on VM

(data-validation) root@postgres-data-validation:~# data-validation validate column --source-conn source --target-conn target --tables-list 'public.realm=public.realm'/root/data-validation/lib/python3.10/site-packages/ibis/backends/postgres/__init__.py:162: UserWarning: Unable to create first/last aggregates: syntax error at or near "AGGREGATE"
LINE 6: CREATE OR REPLACE AGGREGATE public._ibis_first (anyelement) ...
                          ^

  warnings.warn(f"Unable to create first/last aggregates: {e}")
Traceback (most recent call last):
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/data-validation/bin/data-validation", line 8, in <module>
    sys.exit(main())
  File "/root/data-validation/lib/python3.10/site-packages/data_validation/__main__.py", line 633, in main
    validate(args)
  File "/root/data-validation/lib/python3.10/site-packages/data_validation/__main__.py", line 611, in validate
    run(args)
  File "/root/data-validation/lib/python3.10/site-packages/data_validation/__main__.py", line 578, in run
    run_validations(args, config_managers)
  File "/root/data-validation/lib/python3.10/site-packages/data_validation/__main__.py", line 534, in run_validations
    run_validation(config_manager, dry_run=args.dry_run, verbose=args.verbose)
  File "/root/data-validation/lib/python3.10/site-packages/data_validation/__main__.py", line 507, in run_validation
    validator.execute()
  File "/root/data-validation/lib/python3.10/site-packages/data_validation/data_validation.py", line 96, in execute
    result_df = self._execute_validation(
  File "/root/data-validation/lib/python3.10/site-packages/data_validation/data_validation.py", line 270, in _execute_validation
    source_query = validation_builder.get_source_query()
  File "/root/data-validation/lib/python3.10/site-packages/data_validation/validation_builder.py", line 361, in get_source_query
    table = self.config_manager.get_source_ibis_table()
  File "/root/data-validation/lib/python3.10/site-packages/data_validation/config_manager.py", line 342, in get_source_ibis_table
    self._source_ibis_table = clients.get_ibis_table(
  File "/root/data-validation/lib/python3.10/site-packages/data_validation/clients.py", line 134, in get_ibis_table
    return client.table(table_name, database=database_name, schema=schema_name)
  File "/root/data-validation/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 519, in table
    sqla_table = self._get_sqla_table(name, database=database, schema=schema)
  File "/root/data-validation/lib/python3.10/site-packages/ibis/backends/base/sql/alchemy/__init__.py", line 422, in _get_sqla_table
    table = sa.Table(
  File "<string>", line 2, in __new__
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 618, in __new__
    with util.safe_reraise():
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 774, in reflect_table
    for col_d in self.get_columns(
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "<string>", line 2, in get_columns
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3856, in get_columns
    table_oid = self.get_table_oid(
  File "<string>", line 2, in get_table_oid
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 55, in cache
    ret = fn(self, con, *args, **kw)
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3733, in get_table_oid
    c = connection.execute(s, dict(table_name=table_name, schema=schema))
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/root/data-validation/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InFailedSqlTransaction) current transaction is aborted, commands ignored until end of transaction block

[SQL: 
            SELECT c.oid
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE (n.nspname = %(schema)s)
            AND c.relname = %(table_name)s AND c.relkind in
            ('r', 'v', 'm', 'f', 'p')
        ]
[parameters: {'schema': 'public', 'table_name': 'realm'}]
(Background on this error at: https://sqlalche.me/e/14/2j85)
(data-validation) root@postgres-data-validation:~#

**Comment by nehanene15** [comment]
Unable to reproduce. Please re-open if this behavior is seen again.

**Comment by Raniksingh** [comment]
Another user who is doing RDS postgreSQL - AlloyDB validation facing same issue

**Comment by Raniksingh** [comment]
Closing with reference to #1154
