### ISSUE TITLE
row hash validation not working with the current config based on the row validation example

### ISSUE THREAD

**Issue by kenricnguyen** [GoogleCloudPlatform/professional-services-data-validator#1116]
Hi 
My goal is to compare many tables  sitting in the source (MSSQL) and the target (Snowflake) database. I'm doing some tests as below.

I set up the snowflake connection correctly and tested comparing the record count of the same table using the `column` option like this: 
`data-validation validate column -sc snowflake -tc snowflake -tbls MY_SCH.MY_TABLE `
The result of the row count comparison was successful.

However, when I try to run a row comparison like below:
data-validation validate row -sc snowflake -tc snowflake -tbls MY_SCH.MY_TABLE  --primary-keys MY_PRIMARY_KEY --hash '*'
The errors below came up:

```
C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ibis\backends\postgres\registry.py:121: UserWarning: locale specific date formats (%c, %x, %X) are not yet implemented for Windows
  warnings.warn(
C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\third_party\ibis\ibis_oracle\registry.py:160: UserWarning: locale specific date formats (%c, %x, %X) are not yet implemented for Windows
  warnings.warn(
C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\third_party\ibis\ibis_db2\registry.py:192: UserWarning: locale specific date formats (%c, %x, %X) are not yet implemented for Windows
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\Scripts\data-validation-script.py", line 33, in <module>
    sys.exit(load_entry_point('google-pso-data-validator==4.4.0', 'console_scripts', 'data-validation')())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\__main__.py", line 710, in main
    validate(args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\__main__.py", line 688, in validate
    run(args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\__main__.py", line 654, in run
    run_validations(args, config_managers)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\__main__.py", line 597, in run_validations
    run_validation(config_manager, dry_run=args.dry_run, verbose=args.verbose)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\__main__.py", line 570, in run_validation
    validator.execute()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\data_validation.py", line 89, in execute
    result_df = self.execute_recursive_validation(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\data_validation.py", line 232, in execute_recursive_validation
    self._execute_validation(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\data_validation.py", line 270, in _execute_validation
    source_query = validation_builder.get_source_query()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\validation_builder.py", line 363, in get_source_query
    query = self.source_builder.compile(self.validation_type, table)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\query_builder\query_builder.py", line 509, in compile
    table = table.mutate(self.compile_calculated_fields(table, n))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\query_builder\query_builder.py", line 481, in compile_calculated_fields
    return [
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\query_builder\query_builder.py", line 482, in <listcomp>
    field.compile(table)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\data_validation\query_builder\query_builder.py", line 416, in compile
    calc_field = self.expr(*compiled_fields, **self.kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ibis\expr\types\strings.py", line 831, in join
    return cls(self, strings).to_expr()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ibis\common\grounds.py", line 25, in __call__
    return cls.__create__(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ibis\common\grounds.py", line 98, in __create__
    kwargs = cls.__signature__.validate(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ibis\common\annotations.py", line 357, in validate
    this[name] = param.annotation.validate(value, this=this)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ibis\common\annotations.py", line 58, in validate
    return self._validator(arg, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\toolz\functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ibis\common\validators.py", line 509, in tuple_of
    return sequence_of(inner, arg, type=type, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\toolz\functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ibis\common\validators.py", line 467, in sequence_of
    raise IbisTypeError(f'Arg must have at least {min_length} number of elements')
ibis.common.exceptions.IbisTypeError: Arg must have at least 1 number of elements
```

I tried changing the columns, table and connection between MSSQL and Snowflake but they also came out with the same error.

Why is this the case? How do I make it work? 
Thank you

**Comment by kenricnguyen** [comment]
Never mind, I solved it by removing the quotation around the hash parameter value and for the -tbls parameter use Schema.table=Schema.table. For anyone who had the same issue, don't use any quotations in this command.

**Comment by helensilva14** [comment]
Hi @kenricnguyen, thank you for the update and sharing your solution! Indeed, no quotations need to be provided for the tables parameter and when you pass only one value DVT assumes the schema/table are the very same for both source and target.
