### ISSUE TITLE
Row validation throws an error when the data type of primary key is NUMERIC

### ISSUE THREAD

**Issue by sundar-mudupalli-work** [GoogleCloudPlatform/professional-services-data-validator#1119]
When the data type of the primary key is NUMERIC - Row validation throws an error. Consider a table in Oracle defined as follows:
```
SQL> describe pso_data_validator.issue1115;
 Name                                      Null?    Type
 ----------------------------------------- -------- ----------------------------
 ID                                                 NUMBER(38)
 ID_STRING                                          VARCHAR2(10)
 ID_NUMERIC                                         NUMBER(38)
 COL_CHAR_2                                         CHAR(2)
 COL_DATE                                           DATE
 ```
 The following command succeeds
 ```
 data-validation validate row -sc oracle21 -tc oracle21 -tbls=pso_data_validator.issue1115 --primary-keys=id_string --concat='col_char_2,col_date' --filters='TRUNC(COL_DATE)=TRUNC(SYSDATE)'
╒═══════════════════╤═══════════════════╤═════════════════════╤══════════════════════╤════════════════════╤════════════════════╤══════════════════╤═════════════════════╤══════════╕
│ validation_name   │ validation_type   │ source_table_name   │ source_column_name   │ source_agg_value   │ target_agg_value   │ pct_difference   │ validation_status   │ run_id   │
╞═══════════════════╪═══════════════════╪═════════════════════╪══════════════════════╪════════════════════╪════════════════════╪══════════════════╪═════════════════════╪══════════╡
╘═══════════════════╧═══════════════════╧═════════════════════╧══════════════════════╧════════════════════╧════════════════════╧══════════════════╧═════════════════════╧══════════╛
```
While the same command using id_numeric (a numeric data type) fails
```
data-validation validate row -sc oracle21 -tc oracle21 -tbls=pso_data_validator.issue1115 --primary-keys=id_numeric --con
cat='col_char_2,col_date' --filters='TRUNC(COL_DATE)=TRUNC(SYSDATE)'
> /home/user/professional-services-data-validator/env/lib/python3.10/site-packages/data_validation/data_validation.py(89)execute()
-> grouped_fields = self.validation_builder.pop_grouped_fields()
(Pdb) c
Traceback (most recent call last):
  File "/home/user/professional-services-data-validator/env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/user/professional-services-data-validator/env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-00904: "COL_DATE": invalid identifier
[SQL: WITH t0 AS 
(SELECT t6.id AS id, t6.id_string AS id_string, t6.id_numeric AS id_numeric, t6.col_char_2 AS col_char_2, t6.col_date AS col_date, t6.col_char_2 AS cast__col_char_2, to_char(t6.col_date, :to_char_1) AS cast__col_date 
FROM pso_data_validator.issue1115 t6), 
t1 AS 
(SELECT t0.id AS id, t0.id_string AS id_string, t0.id_numeric AS id_numeric, t0.col_char_2 AS col_char_2, t0.col_date AS col_date, t0.cast__col_char_2 AS cast__col_char_2, t0.cast__col_date AS cast__col_date, coalesce(t0.cast__col_char_2, :param_1) AS ifnull__cast__col_char_2, coalesce(t0.cast__col_date, :param_2) AS ifnull__cast__col_date 
FROM t0), 
t2 AS 
(SELECT t1.id AS id, t1.id_string AS id_string, t1.id_numeric AS id_numeric, t1.col_char_2 AS col_char_2, t1.col_date AS col_date, t1.cast__col_char_2 AS cast__col_char_2, t1.cast__col_date AS cast__col_date, t1.ifnull__cast__col_char_2 AS ifnull__cast__col_char_2, t1.ifnull__cast__col_date AS ifnull__cast__col_date, rtrim(t1.ifnull__cast__col_char_2) AS rstrip__ifnull__cast__col_char_2, rtrim(t1.ifnull__cast__col_date) AS rstrip__ifnull__cast__col_date 
FROM t1), 
t3 AS 
(SELECT t2.id AS id, t2.id_string AS id_string, t2.id_numeric AS id_numeric, t2.col_char_2 AS col_char_2, t2.col_date AS col_date, t2.cast__col_char_2 AS cast__col_char_2, t2.cast__col_date AS cast__col_date, t2.ifnull__cast__col_char_2 AS ifnull__cast__col_char_2, t2.ifnull__cast__col_date AS ifnull__cast__col_date, t2.rstrip__ifnull__cast__col_char_2 AS rstrip__ifnull__cast__col_char_2, t2.rstrip__ifnull__cast__col_date AS rstrip__ifnull__cast__col_date, upper(t2.rstrip__ifnull__cast__col_char_2) AS upper__rstrip__ifnull__cast__col_char_2, upper(t2.rstrip__ifnull__cast__col_date) AS upper__rstrip__ifnull__cast__col_date 
FROM t2), 
t4 AS 
(SELECT t3.id AS id, t3.id_string AS id_string, t3.id_numeric AS id_numeric, t3.col_char_2 AS col_char_2, t3.col_date AS col_date, t3.cast__col_char_2 AS cast__col_char_2, t3.cast__col_date AS cast__col_date, t3.ifnull__cast__col_char_2 AS ifnull__cast__col_char_2, t3.ifnull__cast__col_date AS ifnull__cast__col_date, t3.rstrip__ifnull__cast__col_char_2 AS rstrip__ifnull__cast__col_char_2, t3.rstrip__ifnull__cast__col_date AS rstrip__ifnull__cast__col_date, t3.upper__rstrip__ifnull__cast__col_char_2 AS upper__rstrip__ifnull__cast__col_char_2, t3.upper__rstrip__ifnull__cast__col_date AS upper__rstrip__ifnull__cast__col_date, upper__rstrip__ifnull__cast__col_char_2 || upper__rstrip__ifnull__cast__col_date AS concat__all 
FROM t3)
 SELECT t5.concat__all, t5.id_numeric 
FROM (SELECT t4.concat__all AS concat__all, CAST(t4.id_numeric AS VARCHAR2(3000 CHAR)) AS id_numeric 
FROM t4) t5 
WHERE TRUNC(COL_DATE)=TRUNC(SYSDATE)]
[parameters: {'param_1': 'DEFAULT_REPLACEMENT_STRING', 'param_2': 'DEFAULT_REPLACEMENT_STRING', 'to_char_1': 'YYYY-MM-DD HH24:MI:SS'}]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```
This looks very similar to [issue1115](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/1115) which is only seen on Snowflake because the SQL query with the primary key being id_string looks as follows:
```
WITH t0 AS 
(SELECT t5.id AS id, t5.id_string AS id_string, t5.id_numeric AS id_numeric, t5.col_char_2 AS col_char_2, t5.col_date AS col_date, t5.col_char_2 AS cast__col_char_2, to_char(t5.col_date, :to_char_1) AS cast__col_date 
FROM pso_data_validator.issue1115 AS t5), 
t1 AS 
(SELECT t0.id AS id, t0.id_string AS id_string, t0.id_numeric AS id_numeric, t0.col_char_2 AS col_char_2, t0.col_date AS col_date, t0.cast__col_char_2 AS cast__col_char_2, t0.cast__col_date AS cast__col_date, coalesce(t0.cast__col_char_2, :param_1) AS ifnull__cast__col_char_2, coalesce(t0.cast__col_date, :param_2) AS ifnull__cast__col_date 
FROM t0), 
t2 AS 
(SELECT t1.id AS id, t1.id_string AS id_string, t1.id_numeric AS id_numeric, t1.col_char_2 AS col_char_2, t1.col_date AS col_date, t1.cast__col_char_2 AS cast__col_char_2, t1.cast__col_date AS cast__col_date, t1.ifnull__cast__col_char_2 AS ifnull__cast__col_char_2, t1.ifnull__cast__col_date AS ifnull__cast__col_date, rtrim(t1.ifnull__cast__col_char_2) AS rstrip__ifnull__cast__col_char_2, rtrim(t1.ifnull__cast__col_date) AS rstrip__ifnull__cast__col_date 
FROM t1), 
t3 AS 
(SELECT t2.id AS id, t2.id_string AS id_string, t2.id_numeric AS id_numeric, t2.col_char_2 AS col_char_2, t2.col_date AS col_date, t2.cast__col_char_2 AS cast__col_char_2, t2.cast__col_date AS cast__col_date, t2.ifnull__cast__col_char_2 AS ifnull__cast__col_char_2, t2.ifnull__cast__col_date AS ifnull__cast__col_date, t2.rstrip__ifnull__cast__col_char_2 AS rstrip__ifnull__cast__col_char_2, t2.rstrip__ifnull__cast__col_date AS rstrip__ifnull__cast__col_date, upper(t2.rstrip__ifnull__cast__col_char_2) AS upper__rstrip__ifnull__cast__col_char_2, upper(t2.rstrip__ifnull__cast__col_date) AS upper__rstrip__ifnull__cast__col_date 
FROM t2)
 SELECT t4.concat__all, t4.id_string 
FROM (SELECT t3.id AS id, t3.id_string AS id_string, t3.id_numeric AS id_numeric, t3.col_char_2 AS col_char_2, t3.col_date AS col_date, t3.cast__col_char_2 AS cast__col_char_2, t3.cast__col_date AS cast__col_date, t3.ifnull__cast__col_char_2 AS ifnull__cast__col_char_2, t3.ifnull__cast__col_date AS ifnull__cast__col_date, t3.rstrip__ifnull__cast__col_char_2 AS rstrip__ifnull__cast__col_char_2, t3.rstrip__ifnull__cast__col_date AS rstrip__ifnull__cast__col_date, t3.upper__rstrip__ifnull__cast__col_char_2 AS upper__rstrip__ifnull__cast__col_char_2, t3.upper__rstrip__ifnull__cast__col_date AS upper__rstrip__ifnull__cast__col_date, upper__rstrip__ifnull__cast__col_char_2 || upper__rstrip__ifnull__cast__col_date AS concat__all 
FROM t3) AS t4 
WHERE TRUNC(COL_DATE)=TRUNC(SYSDATE)
```
All fixed point data types in Snowflake are implemented as NUMERIC, so if a snowflake has a fixed point data type as a primary key - DVT cannot validate with that key.

**Comment by nj1973** [comment]
If we decide to move the filter earlier in the process in order to fix https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/1115 then I expect this will be fixed too. We should re-test this once 1115 has been resolved.

**Comment by nj1973** [comment]
I tested this again with DVT v5.0.0 and the command completes without the exception.
