### ISSUE TITLE
[TD to BQ] Row validation with -comp-fields fails for date "0001-01-01"

### ISSUE THREAD

**Issue by franklinWhaite** [GoogleCloudPlatform/professional-services-data-validator#1193]
Fields with datatype DATE and value of `0001-01-01` cause unexpected behaviors on `-comp-fields`.

### Scenario 1
If value 0001-01-01 is present in TD but not present in BQ and date_field is used in in `-pk` the following error is produced: 

```
ValueError: You are trying to merge on object and datetime64[ns] columns. 
If you wish to proceed you should use pd.concat
```

### Scenario 2
If the value 0001-01-01 present in both TD and BQ and date_field in `-comp-fields`, then the following error is produced

```
 File "/home/user/professional-services-data-validator/third_party/ibis/ibis_addon/operations.py", line 556, in string_to_epoch
    parsed_ts = isoparse(ts).astimezone(UTC)
ValueError: year 0 is out of range
```

**Comment by nehanene15** [comment]
**Scenario #1:**
The reason for the first scenario is because when comparing the two resulting dataframes of the query results, pandas infers the schema. DATE '0001-01-01' is consider out of bounds so it defaults to an 'object' data type in pandas. Since the out of bounds date is not present in BQ, BQ infers a 'datetime64[ns]` data type.

This only occurs when date_field is a PK. When it is a comparison field, it is not an issue. Not sure if this is a use case that we intend to support... DVT assumes there is a column with unique values that match on source and target. Is there a reason the column is missing in the target?

**Scenario #2:**
Once again, this is considered OOB for `dateutil.parser.isoparse("0001-01-01").astimezone(UTC)`. We can remove the UTC timezone conversion, but that may introduce issues validation accuracy when calculating epoch seconds. Curious what the source/target timezones are in this case.

**Comment by nehanene15** [comment]
A workaround for scenario #1 is to cast the date_field PK to string. That way the dates starting with 0 won't change the inferred data type of the PK column

```
  primary_keys:
  - cast: string
    field_alias: date_field
    source_column: date_field
    target_column: date_field
    ```

**Comment by paraschavda2411** [comment]
Issue still persists, I am getting ValueError: You are trying to merge on object and datetime64[ns] columns. If you wish to proceed you should use pd.concat.

While comparing the Teradata and Bigquery, eff_dt which is date column in source (TD) as well as the destination (BQ). 
One is being converted to **object** while other is **datetime64[ns]** 

Here are the details, for you to recreate this issue and test it :

## Teradata

CREATE TABLE DB.test_2
(src_cd SMALLINT NOT NULL,
sub_src_cd SMALLINT NOT NULL,
veh_company BYTEINT NOT NULL,
veh_serial_no CHAR(17) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
eff_dt DATE FORMAT 'YYYY-MM-DD' NOT NULL,
bus_type CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS,
cantype CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS,
delinq_date DATE FORMAT 'YYYY-MM-DD' COMPRESS
);

## BigQuery 

create table `project.dataset.test_2`
 (src_cd INT64 ,
  sub_src_cd INT64,
  veh_company INT64,
  veh_serial_no STRING(17),
  eff_dt DATE,
  bus_type STRING(2),
  cantype STRING(1),
  delinq_date DATE
)
;

Here is bigquery sample data screenshot : 
<img width="1784" alt="Screenshot 2024-08-02 at 12 23 53 PM" src="https://github.com/user-attachments/assets/deb85bcb-2eb8-416a-abc0-76dcc899d7fc">

## Data Validation Command 
data-validation -v validate row \
-sc TD_CONN \
-tc bq_conn \
-tbls DB.test_2=project.dataset.test_2 \
--primary-keys src_cd,sub_src_cd,veh_company,veh_serial_no,eff_dt \
-comp-fields bus_type,delinq_date


### Teradata
SELECT t0."rstrip__bus_type", t0."delinq_date", t0."src_cd", t0."sub_src_cd",
       t0."veh_company", t0."veh_serial_no", t0."eff_dt"
FROM (
  SELECT t1.*, rtrim(t1."bus_type") AS "rstrip__bus_type"
  FROM DB.test_2 t1
) t0

### BQ
SELECT t0.`rstrip__bus_type`, t0.`delinq_date`, t0.`src_cd`, t0.`sub_src_cd`,
       t0.`veh_company`, t0.`veh_serial_no`, t0.`eff_dt`
FROM (
  SELECT t1.*, rtrim(t1.`bus_type`) AS `rstrip__bus_type`
  FROM `project.dataset.test_2` t1
) t0

### Teradata Source DF 
delinq_date         object
src_cd               int64
sub_src_cd           int64
veh_company          int64
veh_serial_no       object
**eff_dt              object**
dtype: object

### BQ Target DF 
delinq_date                 object
src_cd                       int64
sub_src_cd                   int64
veh_company                  int64
veh_serial_no               object
**eff_dt              datetime64[ns]**
dtype: object


### Stacktrace : 
08/02/2024 06:39:36 AM-INFO: Adding rtrim() to string comparison fields due to Teradata CHAR padding.
08/02/2024 06:39:37 AM-INFO: {'data_client': <third_party.ibis.ibis_teradata.Backend object at 0x7fe0b02405d0>, 'schema_name': 'DB', 'table_name': 'test_2', 'source_query': None}
08/02/2024 06:39:37 AM-INFO: -- ** Source Query ** --
08/02/2024 06:39:37 AM-INFO: SELECT t0."rstrip__bus_type", t0."delinq_date", t0."src_cd", t0."sub_src_cd",
       t0."veh_company", t0."veh_serial_no", t0."eff_dt"
FROM (
  SELECT t1.*, rtrim(t1."bus_type") AS "rstrip__bus_type"
  FROM DB.test_2 t1
) t0
08/02/2024 06:39:37 AM-INFO: {'data_client': <ibis.backends.bigquery.Backend object at 0x7fe0c1944510>, 'schema_name': 'project.dataset', 'table_name': 'test_2', 'target_query': None}
08/02/2024 06:39:37 AM-INFO: -- ** Target Query ** --
08/02/2024 06:39:37 AM-INFO: SELECT t0.`rstrip__bus_type`, t0.`delinq_date`, t0.`src_cd`, t0.`sub_src_cd`,
       t0.`veh_company`, t0.`veh_serial_no`, t0.`eff_dt`
FROM (
  SELECT t1.*, rtrim(t1.`bus_type`) AS `rstrip__bus_type`
  FROM `project.dataset.test_2` t1
) t0
08/02/2024 06:39:39 AM-ERROR: -- ** Logging Source DF ** --
08/02/2024 06:39:39 AM-ERROR: rstrip__bus_type    object
delinq_date         object
src_cd               int64
sub_src_cd           int64
veh_company          int64
veh_serial_no       object
eff_dt              object
dtype: object
08/02/2024 06:39:39 AM-ERROR:   rstrip__bus_type delinq_date  src_cd  sub_src_cd  veh_company                       veh_serial_no      eff_dt
0               NV  0001-01-01      26         529            1  1fa6gsgsdg160qw                     2019-06-03
1               NV  0001-01-01      26         529            1  1fa6gsgsdg160qw                     2019-07-14
2               NV  0001-01-01      26         529            1  1fa6gsgsdg160qw                     2019-09-17
08/02/2024 06:39:39 AM-ERROR: -- ** Logging Target DF ** --
08/02/2024 06:39:39 AM-ERROR: rstrip__bus_type            object
delinq_date                 object
src_cd                       int64
sub_src_cd                   int64
veh_company                  int64
veh_serial_no               object
eff_dt              datetime64[ns]
dtype: object
08/02/2024 06:39:39 AM-ERROR:   rstrip__bus_type delinq_date  src_cd  sub_src_cd  veh_company    veh_serial_no     eff_dt
0               NV  0001-01-01      26         529            1  1fa6gsgsdg160qw 2019-09-17
1               NV  0001-01-01      26         529            1  1fa6gsgsdg160qw 2019-07-14
2               NV  0001-01-01      26         529            1  1fa6gsgsdg160qw 2019-06-03
Traceback (most recent call last):
  File "/home/dvt/venv/bin/data-validation", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dvt/professional-services-data-validator/data_validation/__main__.py", line 727, in main
    validate(args)
  File "/home/dvt/professional-services-data-validator/data_validation/__main__.py", line 705, in validate
    run(args)
  File "/home/dvt/professional-services-data-validator/data_validation/__main__.py", line 671, in run
    run_validations(args, config_managers)
  File "/home/dvt/professional-services-data-validator/data_validation/__main__.py", line 614, in run_validations
    run_validation(config_manager, dry_run=args.dry_run, verbose=args.verbose)
  File "/home/dvt/professional-services-data-validator/data_validation/__main__.py", line 587, in run_validation
    validator.execute()
  File "/home/dvt/professional-services-data-validator/data_validation/data_validation.py", line 96, in execute
    result_df = self.execute_recursive_validation(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/professional-services-data-validator/data_validation/data_validation.py", line 256, in execute_recursive_validation
    self._execute_validation(
  File "/home/dvt/professional-services-data-validator/data_validation/data_validation.py", line 355, in _execute_validation
    raise e
  File "/home/dvt/professional-services-data-validator/data_validation/data_validation.py", line 338, in _execute_validation
    result_df = combiner.generate_report(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/professional-services-data-validator/data_validation/combiner.py", line 77, in generate_report
    differences_df = client.execute(differences_pivot)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/__init__.py", line 307, in execute
    return execute_and_reset(node, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 486, in execute_and_reset
    result = execute(
             ^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 432, in main_execute
    return execute_with_scope(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 219, in execute_with_scope
    result = execute_until_in_scope(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 323, in execute_until_in_scope
    scopes = [
             ^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 324, in <listcomp>
    execute_until_in_scope(
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 323, in execute_until_in_scope
    scopes = [
             ^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 324, in <listcomp>
    execute_until_in_scope(
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 323, in execute_until_in_scope
    scopes = [
             ^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 324, in <listcomp>
    execute_until_in_scope(
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 323, in execute_until_in_scope
    scopes = [
             ^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 324, in <listcomp>
    execute_until_in_scope(
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/core.py", line 351, in execute_until_in_scope
    result = execute_node(
             ^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/trace.py", line 136, in traced_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/backends/pandas/execution/join.py", line 110, in execute_join
    df = pd.merge(
         ^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 110, in merge
    op = _MergeOperation(
         ^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 707, in __init__
    self._maybe_coerce_merge_keys()
  File "/home/dvt/venv/lib/python3.11/site-packages/pandas/core/reshape/merge.py", line 1346, in _maybe_coerce_merge_keys
    raise ValueError(msg)
**ValueError: You are trying to merge on object and datetime64[ns] columns. If you wish to proceed you should use pd.concat**
