### ISSUE TITLE
Unable to add connection for DB2

### ISSUE THREAD

**Issue by manojredward** [GoogleCloudPlatform/professional-services-data-validator#1224]
data-validation connections add --secret-manager-type GCP --secret-manager-project-id db2_dvt_db_info --connection-name db2 DB2 --host '1' --port '60050' --database ' ' --user ' ' --password ' ' --url ibm_db_sa:db2://:60050/
Traceback (most recent call last):
  File "/Users/manojedward/anaconda3/lib/python3.11/site-packages/data_validation/clients.py", line 251, in get_data_client
    data_client = CLIENT_LOOKUP[source_type](**decrypted_connection_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manojedward/anaconda3/lib/python3.11/site-packages/data_validation/clients.py", line 43, in get_client_call
    raise Exception(msg)
Exception: pip install ibm_db_sa

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/manojedward/anaconda3/bin/data-validation", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/manojedward/anaconda3/lib/python3.11/site-packages/data_validation/__main__.py", line 708, in main
    run_connections(args)
  File "/Users/manojedward/anaconda3/lib/python3.11/site-packages/data_validation/__main__.py", line 670, in run_connections
    _ = clients.get_data_client(conn)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manojedward/anaconda3/lib/python3.11/site-packages/data_validation/clients.py", line 257, in get_data_client
    raise exceptions.DataClientConnectionFailure(msg)
data_validation.exceptions.DataClientConnectionFailure: Connection Type "DB2" could not connect: pip install ibm_db_sa
(base) manojedward@QINC-150 ~ %

**Comment by helensilva14** [comment]
Hello @manojredward! Error happened because you need to install a Python library that is listed there. Could you please make sure you have it installed and retry the command to add the DB2 connection?

`Connection Type "DB2" could not connect: pip install ibm_db_sa`

**Comment by manojredward** [comment]
Earlier we have installed ibm_db_sa and ended up with above issue. After that we have install SQLAlchemy in docker and able to resolve that. Thanks for you response
