### ISSUE TITLE
Problem connecting to Impala

### ISSUE THREAD

**Issue by CysOrion** [GoogleCloudPlatform/professional-services-data-validator#1376]
Impala server version: `impalad version 3.2.0-cdh6.3.2 RELEASE`
Python version: `3.12.3`

I keep getting errors when adding an impala connection to DVT. The connection requires no authentication, no ssl and uses binary transportation.

Here are the errors I get with different command settings. 

```
data-validation connections add \
--connection-name impala_conn Impala \
--host xxx.xxx.xxx.xxx
--port 21050 


Traceback (most recent call last):
  File "/home/user/google-dvt/venv/lib/python3.12/site-packages/thrift/transport/TSocket.py", line 150, in read
    buff = self.handle.recv(sz)
           ^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

```

```
data-validation connections add \
--connection-name impala_conn Impala \
--host xxx.xxx.xxx.xxx
--port 21050 
--auth-mechanism NOSASL

12/23/2024 07:32:58 AM-INFO: Using database default as default
12/23/2024 07:32:58 AM-INFO: Pinging the impalad
12/23/2024 07:32:58 AM-INFO: Success! Config output written to /home/user/.config/google-pso-data-validator/prd_impala.connection.json
12/23/2024 07:32:58 AM-INFO: Closing active operation
12/23/2024 07:32:58 AM-ERROR: Failed to open transport (tries_left=3)
Traceback (most recent call last):
  File "/home/user/google-dvt/venv/lib/python3.12/site-packages/thrift/transport/TSocket.py", line 90, in isOpen
    self.handle.settimeout(0)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/google-dvt/venv/lib/python3.12/site-packages/impala/hiveserver2.py", line 1098, in _execute
    open_transport(transport)
  File "/home/user/google-dvt/venv/lib/python3.12/site-packages/impala/hiveserver2.py", line 1162, in open_transport
    if not transport.isOpen():
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.12/site-packages/thrift/transport/TTransport.py", line 152, in isOpen
    return self.__trans.isOpen()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.12/site-packages/thrift/transport/TSocket.py", line 98, in isOpen
    self.handle.settimeout(original_timeout)
OSError: [Errno 9] Bad file descriptor
```

```
data-validation connections add \
--connection-name impala_conn Impala \
--host xxx.xxx.xxx.xxx
--port 21050 
--auth-mechanism NOSASL
--use-ssl False

12/23/2024 07:34:58 AM-WARNING: using legacy validation callback
/home/user/google-dvt/venv/lib/python3.12/site-packages/thrift/transport/TSSLSocket.py:53: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated
  self._context = ssl.SSLContext(ssl_version)
12/23/2024 07:35:43 AM-INFO: Could not connect to ('xxx.xxx.xxx.xxx', 21050)
Traceback (most recent call last):
  File "/home/user/google-dvt/venv/lib/python3.12/site-packages/thrift/transport/TSocket.py", line 137, in open
    handle.connect(sockaddr)
  File "/usr/lib/python3.12/ssl.py", line 1353, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.12/ssl.py", line 1344, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:983: The handshake operation timed out
12/23/2024 07:35:43 AM-ERROR: Could not connect to any of [('xxx.xxx.xxx.xxx', 21050)]

```

**Comment by CysOrion** [comment]
Tested in Python `3.11.11`, same results ...

**Comment by nj1973** [comment]
Hi @CysOrion, are you able to connect directly from Python using the `impyla` library (i.e. outside of DVT)?

**Comment by CysOrion** [comment]
> Hi @CysOrion, are you able to connect directly from Python using the `impyla` library (i.e. outside of DVT)?

Hi @nj1973, I was able to connect and query results.

```
from impala.dbapi import connect

conn = connect(host = "xxx.xxx.xxx.xxx",  port = 21050)
cursor = conn.cursor()
cursor.execute("SELECT * FROM table LIMIT 5")

print(cursor.description) # printed correct results

```

**Comment by nj1973** [comment]
Hi @CysOrion, I just wanted to update you that I have been able to reproduce this myself, it took me a while to create a test environment.

The initial `TimeoutError: timed out` exception is because we have a different default to Impyla, we default auth mechanism to PLAIN instead of NOSASL. So you were correct to add that to your command.

You can see in the subsequent message that the connection file was created successfully:
```
12/23/2024 07:32:58 AM-INFO: Success! Config output written to /home/user/.config/google-pso-data-validator/prd_impala.connection.json
12/23/2024 07:32:58 AM-INFO: Closing active operation
```

We only create the file after successfully connecting. The exception is coming from connection cleanup in Ibis/SQLAlchemy.

So I'll continue to try and figure out how to prevent the exception but I think you should be able to continue testing with the connection created just before the exception was thrown.

**Comment by nj1973** [comment]
A note for my reference, the exception is being throw in `thrift/transport/TSocket.py` here:
```
        try:
            self.handle.settimeout(0) <<<<<<<
            try:
                peeked_bytes = self.handle.recv(1, socket.MSG_PEEK)
            except (socket.error, OSError) as exc:  # on modern python this is just BlockingIOError
                if exc.errno in (errno.EWOULDBLOCK, errno.EAGAIN):
                    return True
                return False
        finally:
            self.handle.settimeout(original_timeout)
```
The line is throwing `OSError` but is outside of the try/except block.

The source of the call is:
```
  /home/user/professional-services-data-validator/env/lib/python3.12/site-packages/impala/hiveserver2.py(179)__del__()
-> self.close_operation()
```

Part of clean up as the calling process is being cleaned up.

**Comment by nj1973** [comment]
@CysOrion , I have a fix for the issue you described on feature branch `1376-impala-tests`, at least it fixes the issue I was able to reproduce. If you are able to test from a cloned repo you could try it to confirm it works for you too.

**Comment by CysOrion** [comment]
Hi @nj1973 , your fixed branch works. It removed the exception when adding impala connections. Thanks!

But when using validation commands, the connection timed out. It could be connection issue in my environment, still figuring it out.

```
data-validation validate column \
--source-conn prd_impala \
--target-conn prd_bq \
--tables-list  store.table_1

01/03/2025 09:59:08 AM-INFO: Using database store as default
01/03/2025 09:59:08 AM-INFO: Pinging the impalad
01/03/2025 09:59:53 AM-ERROR: Failed to open transport (tries_left=3)
Traceback (most recent call last):
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 150, in read
    buff = self.handle.recv(sz)
           ^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/hiveserver2.py", line 1101, in _execute
    return func(request)
           ^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 196, in OpenSession
    return self.recv_OpenSession()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 208, in recv_OpenSession
    (fname, mtype, rseqid) = iprot.readMessageBegin()
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
         ^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 164, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 164, in read
    raise TTransportException(message="unexpected exception", inner=e)
thrift.transport.TTransport.TTransportException: unexpected exception

01/03/2025 10:00:38 AM-ERROR: Failed to open transport (tries_left=2)
Traceback (most recent call last):
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 150, in read
    buff = self.handle.recv(sz)
           ^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/hiveserver2.py", line 1101, in _execute
    return func(request)
           ^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 196, in OpenSession
    return self.recv_OpenSession()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 208, in recv_OpenSession
    (fname, mtype, rseqid) = iprot.readMessageBegin()
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
         ^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 164, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 164, in read
    raise TTransportException(message="unexpected exception", inner=e)
thrift.transport.TTransport.TTransportException: unexpected exception
01/03/2025 10:01:23 AM-ERROR: Failed to open transport (tries_left=1)
Traceback (most recent call last):
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 150, in read
    buff = self.handle.recv(sz)
           ^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/hiveserver2.py", line 1101, in _execute
    return func(request)
           ^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 196, in OpenSession
    return self.recv_OpenSession()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/_thrift_gen/TCLIService/TCLIService.py", line 208, in recv_OpenSession
    (fname, mtype, rseqid) = iprot.readMessageBegin()
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
         ^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TTransport.py", line 164, in read
    self.__rbuf = BufferIO(self.__trans.read(max(sz, self.__rbuf_size)))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/thrift/transport/TSocket.py", line 164, in read
    raise TTransportException(message="unexpected exception", inner=e)
thrift.transport.TTransport.TTransportException: unexpected exception
Traceback (most recent call last):
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/data_validation/clients.py", line 309, in get_data_client
    data_client = CLIENT_LOOKUP[source_type](**decrypted_connection_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/third_party/ibis/ibis_impala/api.py", line 268, in impala_connect
    backend = ibis.impala.connect(
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/ibis/__init__.py", line 97, in connect
    return backend.connect(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/ibis/backends/base/__init__.py", line 530, in connect
    new_backend.reconnect()
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/ibis/backends/base/__init__.py", line 545, in reconnect
    self.do_connect(*self._con_args, **self._con_kwargs)
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/third_party/ibis/ibis_impala/api.py", line 68, in do_connect
    self._ensure_temp_db_exists()
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/ibis/backends/impala/__init__.py", line 840, in _ensure_temp_db_exists
    if name not in self.list_databases():
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/ibis/backends/impala/__init__.py", line 306, in list_databases
    cur = self.raw_sql('SHOW DATABASES')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/ibis/backends/base/sql/__init__.py", line 134, in raw_sql
    cursor = self.con.execute(query)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/ibis/backends/impala/client.py", line 83, in execute
    cursor = self.pool.connect()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 250, in <lambda>
    return lambda crec: creator()
                        ^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/ibis/backends/impala/client.py", line 106, in _new_cursor
    cursor = con.cursor(user=params.get('user'), convert_types=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/hiveserver2.py", line 129, in cursor
    session = self.service.open_session(user, configuration)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/hiveserver2.py", line 1190, in open_session
    resp = self._rpc('OpenSession', req, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/hiveserver2.py", line 1083, in _rpc
    response = self._execute(func_name, request, retry_on_http_error)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/impala/hiveserver2.py", line 1144, in _execute
    raise HiveServer2Error('Failed after retrying {0} times'
impala.error.HiveServer2Error: Failed after retrying 3 times

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/google-dvt/venv/bin/data-validation", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/data_validation/__main__.py", line 702, in main
    validate(args)
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/data_validation/__main__.py", line 678, in validate
    run(args)
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/data_validation/__main__.py", line 636, in run
    run_validations(args, config_managers)
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/data_validation/__main__.py", line 575, in run_validations
    run_validation(config_manager, dry_run=args.dry_run, verbose=args.verbose)
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/data_validation/__main__.py", line 520, in run_validation
    with DataValidation(
         ^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/data_validation/data_validation.py", line 66, in __init__
    self.config_manager = ConfigManager(
                          ^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/data_validation/config_manager.py", line 58, in __init__
    self.source_client = source_client or clients.get_data_client(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/google-dvt/venv/lib/python3.11/site-packages/data_validation/clients.py", line 315, in get_data_client
    raise exceptions.DataClientConnectionFailure(msg)
data_validation.exceptions.DataClientConnectionFailure: Connection Type "Impala" could not connect: Failed after retrying 3 times
01/03/2025 10:01:23 AM-INFO: Closing active operation
```

**Comment by nj1973** [comment]
Hi @CysOrion , that is strange. I presume `prd_impala` is an unsecured cluster and was added with "NOSASL"?

You could check the contents of the connection config file.

**Comment by CysOrion** [comment]
@nj1973 Turns out the time out is due to unstable connection, I can confirm the branch fixed the issue. 

Thanks a lot for your help!

**Comment by nj1973** [comment]
Thanks for the update @CysOrion .

For information the fix has been merged into the develop branch and will be included in the next release.
