### ISSUE TITLE
Filters feature on Teradata breaking after updating from version 1.4 to 1.5.0

### ISSUE THREAD

**Issue by aymanfarhat** [GoogleCloudPlatform/professional-services-data-validator#338]
When trying to use the filters feature, whenever a Teradata DB is a source or destination, the execution of column validation fails. With an exception from `ibis/expr/types.py`: ValueError: The truth value of an Ibis expression is not defined

In this example, source is Teradata and target is BQ.

```
data-validation validate column \
-sc TD_DVT \
-tc BQ_DVT \
-tbls TEST_DB.USA_NAMES_CORRECT=TEST_DB.USA_NAMES_CORRECT \
--filters="state='NY'"
```
When both sc and tc are Teradata it also breaks, execution is successful only works if both source and target are BigQuery. The same command works perfectly for all 3 cases in version 1.4. Here is the exception I get when using Teradata:

```
Traceback (most recent call last):
  File "/Users/aymanf/projects/professional-services-data-validator/env/bin/data-validation", line 33, in <module>
    sys.exit(load_entry_point('google-pso-data-validator==1.5.0', 'console_scripts', 'data-validation')())
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/data_validation/__main__.py", line 379, in main
    validate(args)
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/data_validation/__main__.py", line 358, in validate
    run(args)
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/data_validation/__main__.py", line 339, in run
    run_validations(args, config_managers)
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/data_validation/__main__.py", line 315, in run_validations
    run_validation(config_manager, verbose=args.verbose)
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/data_validation/__main__.py", line 304, in run_validation
    validator.execute()
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/data_validation/data_validation.py", line 94, in execute
    result_df = self._execute_validation(
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/data_validation/data_validation.py", line 256, in _execute_validation
    source_df = self.config_manager.source_client.execute(source_query)
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/client.py", line 220, in execute
    query = self._get_query(query_ast, **kwargs)
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/client.py", line 226, in _get_query
    return self.query_class(self, dml, **kwargs)
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/third_party/ibis/ibis_teradata/client.py", line 41, in __init__
    super().__init__(client, ddl)
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/client.py", line 40, in __init__
    self.compiled_sql = sql.compile()
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/backends/base_sqlalchemy/compiler.py", line 55, in compile
    compiled_queries = [q.compile() for q in self.queries]
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/backends/base_sqlalchemy/compiler.py", line 55, in <listcomp>
    compiled_queries = [q.compile() for q in self.queries]
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/backends/base_sqlalchemy/compiler.py", line 1656, in compile
    where_frag = self.format_where()
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/backends/base_sqlalchemy/compiler.py", line 1804, in format_where
    new_pred = self._translate(pred, permit_subquery=True)
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/backends/base_sqlalchemy/compiler.py", line 1598, in _translate
    return translator.get_result()
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/backends/base_sqlalchemy/compiler.py", line 1362, in get_result
    translated = self.translate(self.expr)
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/backends/base_sqlalchemy/compiler.py", line 1401, in translate
    return formatter(self, expr)
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/third_party/ibis/ibis_addon/operations.py", line 110, in format_hashbytes_bigquery
    if how == "sha256":
  File "/Users/aymanf/projects/professional-services-data-validator/env/lib/python3.8/site-packages/ibis/expr/types.py", line 52, in __bool__
    raise ValueError(
ValueError: The truth value of an Ibis expression is not defined
```
I tried to troubleshoot this on my end, so far, it looks like the equality expression `if how == "sha256":` in `third_party/ibis/ibis_addon/operations.py` is causing this exception to be raised as it looks like the type of `how` in this case is actually an ibis [Expr object](https://github.com/ibis-project/ibis/blob/master/ibis/expr/types.py#L23) rather than a string representing the hash type (which seems what is expected). I'm sensing that `arg, how = expr.op().args` is not assigning the correct value to how on [line 108 in format_hashbytes_bigquery](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/1dba63be87a8e4b4ff63d1753c6197a6ec3411e5/third_party/ibis/ibis_addon/operations.py#L108)

Couldn't go further than this as I'm not very familiar with the code base yet.

**Comment by renzokuken** [comment]
That is unexpected behavior - is it isolated to Teradata or is BigQuery also affected? Similar functionality has been built into BigQuery for a while however the hashing feature isn't widely used yet.

**Comment by aymanfarhat** [comment]
I can confirm that this is isolated to Teradata so far, BQ seems to work fine. I can also confirm that I'm getting this error when running on the latest version of the dev branch today. Here is the pip list of dependencies on my end, in case that might be useful as well.

```
attrs==20.3.0
bitarray==2.3.4
cachetools==4.2.4
certifi==2021.10.8
charset-normalizer==2.0.7
google-api-core==1.31.3
google-api-python-client==1.12.8
google-auth==1.35.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.6
google-cloud-bigquery==2.11.0
google-cloud-bigquery-storage==2.3.0
google-cloud-core==1.7.2
google-cloud-spanner==3.1.0
google-cloud-storage==1.42.2
google-crc32c==1.3.0
google-pso-data-validator==1.5.0
google-resumable-media==1.3.3
googleapis-common-protos==1.53.0
grpc-google-iam-v1==0.12.3
grpcio==1.35.0
httplib2==0.20.1
ibis-bigquery==0.1.1
ibis-framework==1.4.0
idna==3.3
impyla==0.16.3
jellyfish==0.8.2
lazy-object-proxy==1.4.3
libcst==0.3.21
marshmallow==3.10.0
multipledispatch==0.6.0
mypy-extensions==0.4.3
numpy==1.21.3
oauthlib==3.1.1
packaging==21.0
pandas==1.2.3
ply==3.11
proto-plus==1.13.0
protobuf==3.17.3
psycopg2-binary==2.8.6
pyarrow==3.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycryptodome==3.11.0
pydata-google-auth==1.1.0
PyMySQL==1.0.2
pyparsing==2.4.7
python-dateutil==2.8.2
pytz==2021.3
PyYAML==5.4.1
regex==2021.10.23
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
six==1.16.0
SQLAlchemy==1.3.22
sqlparse==0.4.2
tabulate==0.8.9
teradatasql==17.10.0.2
thriftpy2==0.4.14
toolz==0.11.1
typing-extensions==3.10.0.2
typing-inspect==0.7.1
uritemplate==3.0.1
urllib3==1.26.7
```

**Comment by renzokuken** [comment]
Thanks for confirming and providing that list. Integration testing for Teradata has not been part of our automatic build process which I am actively working to address - hopefully that will help reduce the number of issues with our TD integration.

**Comment by renzokuken** [comment]
@aymanfarhat I've gotten integration testing set up internally and have tested using filters with teradata. Currently my test config is passing. Can you please share the yaml configuration generated by your CLI call?

**Comment by aymanfarhat** [comment]
Hello @renzokuken thanks for the update and apologies for the late reply. Here is the yaml generated from my end:

```
result_handler: {}
source: TD_DVT
target: BQ_DVT
validations:
- aggregates:
  - field_alias: count
    source_column: null
    target_column: null
    type: count
  filters:
  - source: state='NY'
    target: state='NY'
    type: custom
  format: table
  labels: []
  schema_name: TEST_DB
  table_name: USA_NAMES_CORRECT
  target_schema_name: TEST_DB
  target_table_name: USA_NAMES_CORRECT
  threshold: 0.0
  type: Column
```

**Comment by nehanene15** [comment]
@aymanfarhat Unfortunately, we were unable to reproduce this issue. The integration tests added [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/tests/system/data_sources/test_teradata.py) were used for testing. Do you have any new findings on this issue?
