### ISSUE TITLE
No processing <int4range> column type in Postgres DB

### ISSUE THREAD

**Issue by letmardi** [GoogleCloudPlatform/professional-services-data-validator#369]
Validation not working with `int4range` column type in Postgres DB  as a source.

```
Traceback (most recent call last):
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 269, in __call__
    func = self._cache[types]
KeyError: (<class 'sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2'>, <class 'sqlalchemy.dialects.postgresql.ranges.INT4RANGE'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/bin/data-validation", line 8, in <module>
    sys.exit(main())
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/data_validation/__main__.py", line 373, in main
    run_validations(args, config_managers)
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/data_validation/__main__.py", line 315, in run_validations
    run_validation(config_manager, verbose=args.verbose)
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/data_validation/__main__.py", line 304, in run_validation
    validator.execute()
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/data_validation/data_validation.py", line 94, in execute
    self.validation_builder, process_in_memory=True
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/data_validation/data_validation.py", line 246, in _execute_validation
    source_query = validation_builder.get_source_query()
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/data_validation/validation_builder.py", line 257, in get_source_query
    query = self.source_builder.compile(**source_config)
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/data_validation/query_builder/query_builder.py", line 386, in compile
    table = clients.get_ibis_table(data_client, schema_name, table_name)
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/data_validation/clients.py", line 130, in get_ibis_table
    return client.table(table_name, database=database_name, schema=schema_name)
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/ibis/backends/postgres/client.py", line 179, in table
    node = self.table_class(alch_table, self, self._schemas.get(name))
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/ibis/backends/base_sqlalchemy/alchemy.py", line 1024, in __init__
    schema = sch.infer(table, schema=schema)
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/ibis/backends/base_sqlalchemy/alchemy.py", line 301, in schema_from_table
    nullable=column.nullable,
  File "/Users/y.ralko/.local/share/virtualenvs/analytics-dbt-7zrpQIZD/lib/python3.7/site-packages/multipledispatch/dispatcher.py", line 275, in __call__
    (self.name, str_signature(types)))
NotImplementedError: Could not find signature for dtype: <PGDialect_psycopg2, INT4RANGE>
```

**Comment by nehanene15** [comment]
Unfortunately Ibis does not support `int4range` data types for Postgres. It can be registered within Ibis [here](https://github.com/ibis-project/ibis/blob/1.4.0/ibis/backends/base_sqlalchemy/alchemy.py#L157) to support it.
