### ISSUE TITLE
Column validation now ignores filters, threshold and labels

### ISSUE THREAD

**Issue by ajwelch4** [GoogleCloudPlatform/professional-services-data-validator#376]
After [this change](https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/345/files#diff-ec3232fc84a73e24bf5cf68f7beb86e56e968c565509c7e07b420d026fd4f09fL143-R185), column validation now ignores filters, threshold and labels.

For example, the following command taken from the README:
```
data-validation validate column   -sc ajw0100-dvt    -tc ajw0100-dvt   -tbls bigquery-public-data.new_york_citibike.citibike_trips    --grouped-columns starttime    --filters "starttime>'2018-05-26':starttime>'2018-05-27'"
```
Now returns:
```
╒══════╤═══════════════════╤═══════════════════╤═══════════════════════════════════════════════════════╤══════════════════════╤════════════════════╤═══════════════════════════════════════════════════════╤══════════════════════╤════════════════════╤═════════════════════════════╤══════════════╤══════════════════╤══════════╕
│      │ validation_name   │ validation_type   │ source_table_name                                     │ source_column_name   │   source_agg_value │ target_table_name                                     │ target_column_name   │   target_agg_value │ group_by_columns            │   difference │   pct_difference │ status   │
╞══════╪═══════════════════╪═══════════════════╪═══════════════════════════════════════════════════════╪══════════════════════╪════════════════════╪═══════════════════════════════════════════════════════╪══════════════════════╪════════════════════╪═════════════════════════════╪══════════════╪══════════════════╪══════════╡
│    0 │ count             │ Column            │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              33402 │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              33402 │ {"starttime": "2015-05-13"} │            0 │                0 │ success  │
├──────┼───────────────────┼───────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼─────────────────────────────┼──────────────┼──────────────────┼──────────┤
│    1 │ count             │ Column            │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              55486 │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              55486 │ {"starttime": "2016-07-13"} │            0 │                0 │ success  │
├──────┼───────────────────┼───────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼─────────────────────────────┼──────────────┼──────────────────┼──────────┤
│    2 │ count             │ Column            │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              17030 │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              17030 │ {"starttime": "2015-12-20"} │            0 │                0 │ success  │
├──────┼───────────────────┼───────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼─────────────────────────────┼──────────────┼──────────────────┼──────────┤
│    3 │ count             │ Column            │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              60155 │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              60155 │ {"starttime": "2017-09-09"} │            0 │                0 │ success  │
├──────┼───────────────────┼───────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼─────────────────────────────┼──────────────┼──────────────────┼──────────┤
│    4 │ count             │ Column            │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              67752 │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              67752 │ {"starttime": "2017-06-28"} │            0 │                0 │ success  │
├──────┼───────────────────┼───────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼─────────────────────────────┼──────────────┼──────────────────┼──────────┤
│    5 │ count             │ Column            │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              35614 │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              35614 │ {"starttime": "2015-12-08"} │            0 │                0 │ success  │
├──────┼───────────────────┼───────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼─────────────────────────────┼──────────────┼──────────────────┼──────────┤
│    6 │ count             │ Column            │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              63635 │ bigquery-public-data.new_york_citibike.citibike_trips │                      │              63635 │ {"starttime": "2017-10-07"} │            0 │                0 │ success  │
├──────┼───────────────────┼───────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼───────────────────────────────────────────────────────┼──────────────────────┼────────────────────┼─────────────────────────────┼──────────────┼──────────────────┼──────────┤
...
```
Note `starttime` does not respect the filter.

**Comment by ajwelch4** [comment]
This also broke schema validation:
```
> data-validation validate schema   -sc ajw0100-dvt    -tc ajw0100-dvt   -tbls bigquery-public-data.new_york_citibike.citibike_trips                            

Traceback (most recent call last):
  File "/home/ajwelch/professional-services-data-validator/env/bin/data-validation", line 33, in <module>
    sys.exit(load_entry_point('google-pso-data-validator', 'console_scripts', 'data-validation')())
  File "/home/ajwelch/professional-services-data-validator/data_validation/__main__.py", line 455, in main
    validate(args)
  File "/home/ajwelch/professional-services-data-validator/data_validation/__main__.py", line 433, in validate
    run(args)
  File "/home/ajwelch/professional-services-data-validator/data_validation/__main__.py", line 388, in run
    config_managers = build_config_managers_from_args(args)
  File "/home/ajwelch/professional-services-data-validator/data_validation/__main__.py", line 186, in build_config_managers_from_args
    if args.filters:
AttributeError: 'Namespace' object has no attribute 'filters'
```
