### ISSUE TITLE
Unable to add Snowflake Connection

### ISSUE THREAD

**Issue by sfc-gh-gbhawsar** [GoogleCloudPlatform/professional-services-data-validator#519]
I am unable add Snowflake connection, please take a look at below; note that I already have snowflake-connector-python , snowflake-sqlalchemy packages installed in my environment. Replaced sensitive information with *

Update:
**_Before installing snowflake-sqlalchemy package_**
(venv) (base) ******@******** GoogleDVT % data-validation connections add --connection-name sf_cas2 Raw --json '
{
    "source_type": "Snowflake",
    "user": "******",
    "password": "***",
    "account": "***",
    "database":"***",
    "schema": "***"
}'
Traceback (most recent call last):
  File "/Users/******/GoogleDVT/venv/lib/python3.8/site-packages/data_validation/clients.py", line 240, in get_data_client
    data_client = CLIENT_LOOKUP[source_type](**connection_config)
  File "/Users/******/GoogleDVT/venv/lib/python3.8/site-packages/data_validation/clients.py", line 56, in get_client_call
    raise Exception(msg)
Exception: pip install snowflake-connector-python

**During handling of the above exception, another exception occurred:**

Traceback (most recent call last):
  File "/Users/******/GoogleDVT/venv/bin/data-validation", line 8, in <module>
    sys.exit(main())
  File "/Users/******/GoogleDVT/venv/lib/python3.8/site-packages/data_validation/__main__.py", line 497, in main
    run_connections(args)
  File "/Users/******/GoogleDVT/venv/lib/python3.8/site-packages/data_validation/__main__.py", line 455, in run_connections
    _ = clients.get_data_client(conn)
  File "/Users/******/GoogleDVT/venv/lib/python3.8/site-packages/data_validation/clients.py", line 246, in get_data_client
    raise exceptions.DataClientConnectionFailure(msg)
data_validation.exceptions.DataClientConnectionFailure: Connection Type "Snowflake" could not connect: pip install snowflake-connector-python
(venv) (base) ******@******* GoogleDVT % 

**_Error after installing snowflake-sqlalchemy package_**
Traceback (most recent call last):
  File "/Users/******/GoogleDVT/venv/bin/data-validation", line 5, in <module>
    from data_validation.__main__ import main
  File "/Users/******/GoogleDVT/venv/lib/python3.8/site-packages/data_validation/__main__.py", line 21, in <module>
    from data_validation import (
  File "/Users/******/GoogleDVT/venv/lib/python3.8/site-packages/data_validation/clients.py", line 20, in <module>
    import ibis
  File "/Users/******/GoogleDVT/venv/lib/python3.8/site-packages/ibis/__init__.py", line 36, in <module>
    from ibis.backends import sqlite  # noqa: F401
  File "/Users/******/GoogleDVT/venv/lib/python3.8/site-packages/ibis/backends/sqlite/__init__.py", line 16, in <module>
    from .client import SQLiteClient
  File "/Users/******/GoogleDVT/venv/lib/python3.8/site-packages/ibis/backends/sqlite/client.py", line 11, in <module>
    import ibis.backends.base_sqlalchemy.alchemy as alch
  File "/Users/******/GoogleDVT/venv/lib/python3.8/site-packages/ibis/backends/base_sqlalchemy/alchemy.py", line 47, in <module>
    dt.Binary: sa.Binary,
AttributeError: module 'sqlalchemy' has no attribute 'Binary'

**Comment by nehanene15** [comment]
This is similar to Issue #389 

Can you try pinning the snowlfake-sqlalchemy version? 
`pip install snowflake-sqlalchemy==1.2.5`

**Comment by sfc-gh-gbhawsar** [comment]
Hi, I already had snowflake-sqlalchemy 1.3.4, but uninstalled and **Successfully installed snowflake-sqlalchemy-1.2.5. Still getting the same error.** Seems like the reporters in Issue https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/389 were not able to confirm if the fix worked for them..

Appreciate your time and help with this. I look forward to your response.

**Comment by ctezna** [comment]
Hi has anyone been able to create Snowflake connection? I am having same issues as above and have followed all steps.

**Comment by sfc-gh-gbhawsar** [comment]
@ctezna I am still not able to form a connection.. @nehanene15 Checking if you have any update on my previous comment. Appreciate your help!

**Comment by nehanene15** [comment]
Unfortunately, the core engineering team does not have access to spin up a Snowflake instance for testing and developing this tool. The original Ibis connector was built by a partner and is out of date. 

Feel free to contribute to update the connector. Until then, we will pull Snowflake from the supported connections.

**Comment by emptyr1** [comment]
Did anyone have any luck with this?

**Comment by helensilva14** [comment]
Closing this issue because since v4.0.0 (https://github.com/GoogleCloudPlatform/professional-services-data-validator/releases/tag/v4.0.0) we fully support validations for Snowflake!
