### ISSUE TITLE
Connection Type "Impala" could not connect: Bad status: 3 (b'Unsupported mechanism type PLAIN')

### ISSUE THREAD

**Issue by WMjf** [GoogleCloudPlatform/professional-services-data-validator#546]
Hi Team
Please  your support  with this  topic I am trying to connect via impala to a database that requires password and user and additionally I think it is not plain it would be GSSAPI since it possibly requires the certificate do you have any idea about this or if it has a possible string connection
I am using  
this  
data-validation connections add --connection-name HDDEV1 Impala --host XXXXXXX --port 10000 

Traceback (most recent call last):
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/ibis/backends/impala/client.py", line 145, in _get_cursor
    cursor = self.connection_pool.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/data_validation/clients.py", line 238, in get_data_client
    data_client = CLIENT_LOOKUP[source_type](**connection_config)
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/third_party/ibis/ibis_impala/api.py", line 40, in impala_connect
    return connect(
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/ibis/backends/impala/__init__.py", line 123, in connect
    client = ImpalaClient(con, hdfs_client=hdfs_client)
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/ibis/backends/impala/client.py", line 805, in __init__
    self._ensure_temp_db_exists()
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/ibis/backends/impala/client.py", line 1408, in _ensure_temp_db_exists
    if not self.exists_database(name):
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/ibis/backends/impala/client.py", line 923, in exists_database
    return bool(self.list_databases(like=name))
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/ibis/backends/impala/client.py", line 1018, in list_databases
    with self._execute(statement, results=True) as cur:
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/ibis/client.py", line 155, in _execute
    cur = self.con.execute(query)
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/ibis/backends/impala/client.py", line 116, in execute
    cursor = self._get_cursor()
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/ibis/backends/impala/client.py", line 148, in _get_cursor
    return self._new_cursor()
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/ibis/backends/impala/client.py", line 161, in _new_cursor
    con = impyla.connect(database=self.database, **params)
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/impala/dbapi.py", line 159, in connect
    service = hs2.connect(host=host, port=port,
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/impala/hiveserver2.py", line 862, in connect
    transport.open()
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/thrift_sasl/__init__.py", line 95, in open
    raise TTransportException(type=TTransportException.NOT_OPEN,
thrift.transport.TTransport.TTransportException: Bad status: 3 (b'Unsupported mechanism type PLAIN')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/j0g0ril/anaconda3/envs/dvt_env/bin/data-validation", line 8, in <module>
    sys.exit(main())
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/data_validation/__main__.py", line 497, in main
    run_connections(args)
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/data_validation/__main__.py", line 455, in run_connections
    _ = clients.get_data_client(conn)
  File "/home/j0g0ril/anaconda3/envs/dvt_env/lib/python3.9/site-packages/data_validation/clients.py", line 244, in get_data_client
    raise exceptions.DataClientConnectionFailure(msg)
data_validation.exceptions.DataClientConnectionFailure: Connection Type "Impala" could not connect: Bad status: 3 (b'Unsupported mechanism type PLAIN')
(dvt_env) [j0g0ril@CAMCUSTDB6rove1y1 py]$

**Comment by nehanene15** [comment]
You can [change the auth_mechanism](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#hive) type when creating a connection: `data-validation connections add --connection-name HDDEV1 Impala --host XXXXXXX --port 10000 --auth-mechanism 'GSSAPI'`

We use the Ibis and the impyla client to connect, and these parameters can be exposed when creating a connection: https://github.com/ibis-project/ibis/blob/1.4.0/ibis/backends/impala/__init__.py#L41. Through the CLI, we only expose host, port, database, and auth_mechanism
