### ISSUE TITLE
TypeError: The datatype of value frozenset(...) cannot be inferred, try passing it explicitly with the `type` keyword.

### ISSUE THREAD

**Issue by RajeevGCP** [GoogleCloudPlatform/professional-services-data-validator#553]
(venv) vn53you@dvtx-test-m:~/dvt_wmt$ data-validation validate row -sc wmt_hive -tc wmt_hive_prod -tbls k1_repl_dl_tables.wmt_k1_repl_safety_stk_event_adj=k1_repl_dl_tables.wmt_k1_repl_safety_stk_event_adj_prod_copy -pk 'safety_stk_event_nm,safety_stk_event_eff_dt' -comp-fields 'geo_region_cd' -rr -rbs 10
Without an HDFS connection, certain functionality may be disabled
Without an HDFS connection, certain functionality may be disabled
Without an HDFS connection, certain functionality may be disabled
Without an HDFS connection, certain functionality may be disabled
Traceback (most recent call last):
  File "/home/vn53you/dvt_wmt/venv/bin/data-validation", line 8, in <module>
    sys.exit(main())
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/__main__.py", line 507, in main
    validate(args)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/__main__.py", line 485, in validate
    run(args)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/__main__.py", line 445, in run
    run_validations(args, config_managers)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/__main__.py", line 424, in run_validations
    run_validation(config_manager, verbose=args.verbose)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/__main__.py", line 413, in run_validation
    validator.execute()
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/data_validation.py", line 90, in execute
    self.validation_builder, grouped_fields
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/data_validation.py", line 219, in execute_recursive_validation
    validation_builder, process_in_memory=process_in_memory
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/data_validation.py", line 286, in _execute_validation
    source_query = validation_builder.get_source_query()
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/validation_builder.py", line 371, in get_source_query
    query = self.source_builder.compile(**source_config)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/query_builder/query_builder.py", line 496, in compile
    compiled_filters = self.compile_filter_fields(table)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/query_builder/query_builder.py", line 452, in compile_filter_fields
    return [field.compile(table) for field in self.filters]
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/query_builder/query_builder.py", line 452, in <listcomp>
    return [field.compile(table) for field in self.filters]
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/data_validation/query_builder/query_builder.py", line 191, in compile
    return self.expr(self.left, self.right)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/ibis/expr/api.py", line 970, in isin
    op = ops.Contains(arg, values)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/ibis/expr/operations.py", line 2422, in __init__
    super().__init__(value, options)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/ibis/expr/signature.py", line 181, in __init__
    for name, value in self.signature.validate(*args, **kwargs):
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/ibis/expr/signature.py", line 129, in validate
    value = argument.validate(arg_value, name=name)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/ibis/expr/signature.py", line 88, in validate
    return self.validator(value)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/ibis/expr/rules.py", line 96, in one_of
    return inner(arg)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/ibis/expr/rules.py", line 200, in value
    arg = ir.literal(arg)
  File "/home/vn53you/dvt_wmt/venv/lib/python3.7/site-packages/ibis/expr/types.py", line 1229, in literal
    'passing it explicitly with the `type` keyword.'.format(value)
TypeError: The datatype of value frozenset({b'K1_DPTO92TOPSFORMATO_RCAST_SV', b'D95 Thanksgiving-Christmas', b'K1_BALAN_PX_DC7423_A0M0W30', b'CA SSCOV 0003D ADJ011521', b'K1 ALAS DORADAS SV MSOSA2', b'MX_D15_RGE_PV3_19_4', b'MX_D13_MYMORAL_BODEGA_11102016', b'TEM_MARGARINA_P1', b'K1_SSTEMPLATE_Dism2D_E1PINED_HN', b'CA_RRM_REDUCE_Cov'}) cannot be inferred, try passing it explicitly with the `type` keyword.

**Comment by nehanene15** [comment]
What is the data type of column 'geo_region_cd'? Are you seeing this error with other validations using the same PKs?
