### ISSUE TITLE
Issue while performing schema & data validations for teradata to bq with google-pso-data-validator==2.7.0

### ISSUE THREAD

**Issue by vasu2809** [GoogleCloudPlatform/professional-services-data-validator#664]
Hi Team,

We were running a workflow for DVT to perform schema, row and column validations for

Source - Teradata
Target - Bigquery

It was working fine till end of last month, our requirements.txt for running DVT on Cloud Run and Kubernetes Pod Operator does not mention specific version and now it has started to install google-pso-data-validator==2.7.0 which was released on Jan 6th I believe.

Since this update, we are receiving the below error while executing dvt against source DB which was working fine earlier.

**teradatasql.OperationalError: [Version 17.20.0.10] [Session 0] [Teradata Database] [Error 8019] The parcel stream is invalid.**

On reverting the cli to version 2.6.0, it starts working fine

**pip install google-pso-data-validator==2.6.0**

Full log file - [error.txt](https://github.com/GoogleCloudPlatform/professional-services-data-validator/files/10457674/error.txt)

 data-validation connections add --connection-name BigQuery_CONN BigQuery --project-id pso-e2e-sql

data-validation connections add --connection-name Teradata_CONN Teradata --host 34.66.209.133 --port 1025 --user-name test --password test

data-validation validate schema  -sc Teradata_CONN -tc BigQuery_CONN -tbls test.party=pso-e2e-sql.e2e_data.party
data-validation validate schema  -sc Teradata_CONN -tc BigQuery_CONN -tbls test.party=pso-e2e-sql.e2e_data.party
Traceback (most recent call last):
  File "/home/user/atc/professional-services-data-validator/venv/lib/python3.10/site-packages/pandas/io/sql.py", line 2056, in execute
    cur.execute(*args, **kwargs)
  File "/home/user/atc/professional-services-data-validator/venv/lib/python3.10/site-packages/teradatasql/__init__.py", line 686, in execute
    self.executemany (sOperation, None, ignoreErrors)
  File "/home/user/atc/professional-services-data-validator/venv/lib/python3.10/site-packages/teradatasql/__init__.py", line 933, in executemany
    raise OperationalError (sErr)
**teradatasql.OperationalError: [Version 17.20.0.10] [Session 0] [Teradata Database] [Error 8019] The parcel stream is invalid.**
 at gosqldriver/teradatasql.formatError ErrorUtil.go:88
 at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError ErrorUtil.go:216
 at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError ErrorUtil.go:232
 at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:812
 at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:2221
 at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:809
 at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:668
 at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122
 at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:1316
 at database/sql.ctxDriverQuery ctxutil.go:48
 at database/sql.(*DB).queryDC.func1 sql.go:1759
 at database/sql.withLock sql.go:3437
 at database/sql.(*DB).queryDC sql.go:1754
 at database/sql.(*Conn).QueryContext sql.go:2013
 at main.goCreateRows goside.go:666
 at _cgoexp_092f630b41aa_goCreateRows _cgo_gotypes.go:340
 at runtime.cgocallbackg1 cgocall.go:314
 at runtime.cgocallbackg cgocall.go:233
 at runtime.cgocallback asm_amd64.s:971
 at runtime.goexit asm_amd64.s:1571

**Comment by nehanene15** [comment]
I believe this was introduced with this change: https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/637/files#diff-ce217c386e702709267508ebe1bc725106c6bcba326c1ccb29951d506855ae6aR65

Version 2.7.0 should work when providing 'logmech' to the connection string like so:
data-validation connections add --connection-name Teradata_CONN Teradata --host 34.66.209.133 --port 1025 --user-name test --password test --logmech 'TD2'

We will work on a fix to make logmech optional.
