### ISSUE TITLE
FR: Error parsing Impala result

### ISSUE THREAD

**Issue by roderickyao** [GoogleCloudPlatform/professional-services-data-validator#72]
It seems to parse Impala result with some trouble.

```
Without an HDFS connection, certain functionality may be disabled
Traceback (most recent call last):
  File "/home/bot-hadoop/hh-working/python36_env/bin/data-validation", line 8, in <module>
    sys.exit(main())
  File "/home/bot-hadoop/hh-working/python36_env/lib64/python3.6/site-packages/data_validation/__main__.py", line 282, in main
    config_managers = build_config_managers_from_args(args)
  File "/home/bot-hadoop/hh-working/python36_env/lib64/python3.6/site-packages/data_validation/__main__.py", line 184, in build_config_managers_from_args
    configs.append(build_config_from_args(args, config_manager))
  File "/home/bot-hadoop/hh-working/python36_env/lib64/python3.6/site-packages/data_validation/__main__.py", line 146, in build_config_from_args
    config_manager.append_aggregates(get_aggregate_config(args, config_manager))
  File "/home/bot-hadoop/hh-working/python36_env/lib64/python3.6/site-packages/data_validation/__main__.py", line 129, in get_aggregate_config
    "count", col_args, None
  File "/home/bot-hadoop/hh-working/python36_env/lib64/python3.6/site-packages/data_validation/config_manager.py", line 245, in build_config_column_aggregates
    source_table = self.get_source_ibis_table()
  File "/home/bot-hadoop/hh-working/python36_env/lib64/python3.6/site-packages/data_validation/config_manager.py", line 134, in get_source_ibis_table
    self.source_table, database=self.source_schema
  File "/home/bot-hadoop/hh-working/python36_env/lib64/python3.6/site-packages/ibis/client.py", line 115, in table
    schema = self._get_table_schema(qualified_name)
  File "/home/bot-hadoop/hh-working/python36_env/lib64/python3.6/site-packages/ibis/impala/client.py", line 1557, in _get_table_schema
    return self.get_schema(tname)
  File "/home/bot-hadoop/hh-working/python36_env/lib64/python3.6/site-packages/ibis/impala/client.py", line 1028, in get_schema
    ibis_types = [udf.parse_type(type.lower()) for type in types]
  File "/home/bot-hadoop/hh-working/python36_env/lib64/python3.6/site-packages/ibis/impala/client.py", line 1028, in <listcomp>
    ibis_types = [udf.parse_type(type.lower()) for type in types]
  File "/home/bot-hadoop/hh-working/python36_env/lib64/python3.6/site-packages/ibis/impala/udf.py", line 336, in parse_type
    raise Exception(t)
Exception: struct<
  program:struct<
    id:string,
    name:string,
    version:string,
    version_info:struct<
      major_version:int,
      minor_version:int,
      patch_version:int,
      prerelease:string
    >,
    sdk:struct<
      name:string,
      version:string,
      version_info:struct<
        major_version:int,
        minor_version:int,
        patch_version:int,
        prerelease:string
      >
    >
  >,
  source_time:bigint,
  time_offset:bigint,
  host:struct<
    id:string,
    name:string,
    type:string,
    site:string,
    platform:string,
    arch:string,
    os_name:string,
    os_version:string,
    tag:array<string>
  >,
...........
>
```

**Comment by nehanene15** [comment]
While we do not support structs, you are able to run column and row level validations on Impala/Hive that exclude struct or array columns by specifying columns in your validation. (i.e `-sum col_a,col_b` or `-hash col_a,col_c`). This is supported in PR #407 

We have Issue #88 open for supporting complex data types.
