### ISSUE TITLE
validate row: Issue with strftime for BigQuery DATETIME column

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/professional-services-data-validator#727]
This is a knock on effect of issue https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/680 which now uses `strftime` instead of `cast` when comparing date based columns.

Test table:
```
CREATE TABLE `dvt_test`.`dvt_dates`
(   id              INT NOT NULL
,   col_date        DATE
,   col_datetime    DATETIME
,   col_tstz        TIMESTAMP
);
INSERT INTO dvt_test.dvt_dates VALUES
(1,DATE '1970-01-01',DATETIME '1970-01-01 00:00:01'
,TIMESTAMP '1970-01-01 00:00:01+01:00');
```

If we validate `col_date` or `col_tstz` columns the status is success.
If we validate the DATETIME column `col_datetime` then an exception is thrown by BigQuery:
```
data-validation validate row -sc bq -tc bq -tbls=dvt_test.dvt_dates=dvt_test.dvt_dates --primary-keys id --concat 'col_datetime'
...
google.api_core.exceptions.BadRequest: 400
No matching signature for function FORMAT_TIMESTAMP for argument types: STRING, DATETIME, STRING. Supported signatures: FORMAT_TIMESTAMP(STRING, TIMESTAMP, [STRING]); FORMAT_TIMESTAMP(STRING, DATETIME) at [16:18]
```

This is because the `ibis-bigquery` package only caters for FORMAT_DATE or FORMAT_TIMESTAMP and BigQuery does not implicitly cast DATETIME to TIMESTAMP.

**Comment by nj1973** [comment]
At the point where the SQL function is constructed we don't have access to the BigQuery schema, only the Ibis one which is `Date` or `Timestamp`. Therefore we don't know which format function to use.

There are a couple of potential fixes for this but they are both in `ibis_bigquery/compiler.py compiles_strftime()`, i.e. outside of the DVT repo. 

1) Cast the expression argument of FORMAT_TIMESTAMP to a TIMESTAMP. For example:
```
    if isinstance(arg_type, dt.Timestamp):
-        return "FORMAT_{}({}, {}, {!r})".format(
+        return "FORMAT_{}({}, TIMESTAMP({}), {!r})".format(
```
This works for both DATETIME and TIMESTAMP inputs.
```
SELECT FORMAT_TIMESTAMP('%Y-%m-%d %H:%M:%S', TIMESTAMP(CURRENT_DATETIME()), 'UTC');
2023-02-16 17:22:16

SELECT FORMAT_TIMESTAMP('%Y-%m-%d %H:%M:%S', TIMESTAMP(CURRENT_TIMESTAMP()), 'UTC');
2023-02-16 17:22:37
```

2) Use FORMAT_DATETIME (which accepts a TIMESTAMP expression) and remove the time zone parameter unless one is specified:
```
-        return "FORMAT_{}({}, {}, {!r})".format(
-            strftime_format_func_name,
-            fmt_string,
-            arg_formatted,
-            arg_type.timezone if arg_type.timezone is not None else "UTC",
-        )
+        if arg_type.timezone is None:
+            return "FORMAT_DATETIME({}, {})".format(
+                fmt_string,
+                arg_formatted
+            )
+        else:
+            return "FORMAT_{}({}, {}, {!r})".format(
+                strftime_format_func_name,
+                fmt_string,
+                arg_formatted,
+                arg_type.timezone
+            )
```
Examples of FORMAT_DATETIME accepting both TIMESTAMP and DATETIME expressions:
```
SELECT FORMAT_DATETIME('%Y-%m-%d %H:%M:%S', CURRENT_TIMESTAMP());
2023-02-16 17:43:04

SELECT FORMAT_DATETIME('%Y-%m-%d %H:%M:%S', CURRENT_DATETIME());
2023-02-16 17:43:28
```

**Comment by mohdt786** [comment]
There seems to be an effect on running `validate custom-query row` commands too

1. Switching to commit #720 
`git checkout 0de823b`

2. Running `validate custom-query` command:
```
data-validation validate custom-query --custom-query-type row --source-query-file source_query.sql --target-query-file target_query.sql -sc my_bq_conn -tc my_bq_conn   --hash '*' --primary-keys station_id
```
### Source query: 
`select station_id from 'bigquery-public-data.new_york_citibike.citibike_stations'`

### Target query: 
`select station_id from 'bigquery-public-data.new_york_citibike.citibike_stations'`

Here only `station_id` is selected which is of type `STRING`. 

Same issue is caused when the following query is used:
`select * from 'bigquery-public-data.new_york_citibike.citibike_stations'`
## Error:
```
Traceback (most recent call last):
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/bin/data-validation", line 8, in <module>
    sys.exit(main())
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/data_validation/__main__.py", line 600, in main
    validate(args)
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/data_validation/__main__.py", line 576, in validate
    run(args)
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/data_validation/__main__.py", line 532, in run
    config_managers = build_config_managers_from_args(args)
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/data_validation/__main__.py", line 304, in build_config_managers_from_args
    config_manager = build_config_from_args(args, config_manager)
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/data_validation/__main__.py", line 186, in build_config_from_args
    config_manager.append_calculated_fields(get_calculated_config(args, config_manager))
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/data_validation/__main__.py", line 128, in get_calculated_config
    fields = config_manager.build_dependent_aliases("hash", col_list)
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/data_validation/config_manager.py", line 822, in build_dependent_aliases
    col = self._apply_base_cast_overrides(column, col)
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/data_validation/config_manager.py", line 730, in _apply_base_cast_overrides
    k: v for k, v in self.get_target_ibis_table().schema().items()
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/data_validation/config_manager.py", line 346, in get_target_ibis_table
    self._target_ibis_table = clients.get_ibis_table(
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/data_validation/clients.py", line 147, in get_ibis_table
    return client.table(table_name, database=schema_name)
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/ibis_bigquery/client.py", line 425, in table
    t = super().table(name, database=database)
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/ibis/client.py", line 119, in table
    qualified_name = self._fully_qualified_name(name, database)
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/ibis_bigquery/client.py", line 440, in _fully_qualified_name
    project, dataset = self._parse_project_and_dataset(database)
  File "/usr/local/google/home/mohammedturky/Desktop/professional-services-data-validator/venv/lib/python3.10/site-packages/ibis_bigquery/client.py", line 409, in _parse_project_and_dataset
    raise ValueError("Unable to determine BigQuery dataset.")
ValueError: Unable to determine BigQuery dataset.
```

The same query is working successfully for previous commits
Eg: `git checkout 47154b4`

**Comment by nj1973** [comment]
@mohdt786, I don't think this is related to the specific error you are seeing. If you copy and run the query from your file into a BigQuery console you'll see the same message:
```
select station_id from 'bigquery-public-data.new_york_citibike.citibike_stations'
...
Syntax error: Unexpected string literal 'bigquery-public-data.new_york_citibike.citibike_...' at [1:24]
```

I believe the problem is you have transposed backticks to single quotes.

**Comment by mohdt786** [comment]
I had just put the single quotes for readability, I actually used backticks in my query file.
In markdown having backticks twice resulted in unformatted code, so I replaced that with single quotes for the comment.

Moreover, I am able to successfully run the query in previous commits

**Comment by nj1973** [comment]
@mohdt786 OK thanks. I'm going to create a new issue for the problem you have discovered because the fix will be in the code changes I made for issue 680. This issue's fix relates to `ibis_bigquery` code which may be harder to work around.
