### ISSUE TITLE
Column validation fails for tables with different schema

### ISSUE THREAD

**Issue by kangshung** [GoogleCloudPlatform/professional-services-data-validator#993]
When I try to validate tables with schemas that are 90% same, instead of getting a nice comparison of what is possible, dvt returns a KeyError on the column name that exists in only 1 of the tbls.

```
❯ data-validation validate column -sc Hive_nonprod -tc BigQuery_nonprod -tbls xxx.yyy=xxx.yyy --count="*"
09/19/2023 09:54:29 AM-INFO: Using database default as default
09/19/2023 09:54:29 AM-INFO: Pinging the impalad
Traceback (most recent call last):
  File "/home/damian/.local/bin/data-validation", line 8, in <module>
    sys.exit(main())
  File "/home/damian/.local/lib/python3.10/site-packages/data_validation/__main__.py", line 582, in main
    validate(args)
  File "/home/damian/.local/lib/python3.10/site-packages/data_validation/__main__.py", line 560, in validate
    run(args)
  File "/home/damian/.local/lib/python3.10/site-packages/data_validation/__main__.py", line 523, in run
    config_managers = build_config_managers_from_args(args)
  File "/home/damian/.local/lib/python3.10/site-packages/data_validation/__main__.py", line 279, in build_config_managers_from_args
    config_manager = build_config_from_args(args, config_manager)
  File "/home/damian/.local/lib/python3.10/site-packages/data_validation/__main__.py", line 232, in build_config_from_args
    config_manager.append_aggregates(get_aggregate_config(args, config_manager))
  File "/home/damian/.local/lib/python3.10/site-packages/data_validation/__main__.py", line 89, in get_aggregate_config
    aggregate_configs += config_manager.build_config_column_aggregates(
  File "/home/damian/.local/lib/python3.10/site-packages/data_validation/config_manager.py", line 691, in build_config_column_aggregates
    casefold_target_columns[column]
KeyError: 'src_inserted_at'
09/19/2023 09:54:32 AM-INFO: Closing active operation
```

I do not see any mentions in documentation about this requirement.

Same problem appears when I try different types of aggregates, or choose columns that exist in both sources (instead of *).

**Comment by nehanene15** [comment]
We fixed this issue in #974 and it will be included in the next release. You can also pull the latest develop branch and run `pip install . ` to start testing the fix now.
